insert into "users" ( "firstName", "lastName", "email", "hashedPassword", "phoneNumber")
values ('Paolo', 'Di Martino', 'paolo.dimartino@outlook.it', 'password1', '3331234567');

insert into "boats" ("boatId", "name", "model", "speed", "motorization", "length", "capacity", "beds", "kitchen", "imageUrl", "internal1", "internal2", "internal3" )
values (1, 'Diana', 'Sorrento 32 Hard Top', '32 Knots','2 x 315 hp Ebd - Yanmar', '9,60 mt', 10, '2 + 2', 1, '/img/fleet/diana/diana1.jpg','/img/fleet/diana/diana2.jpg','/img/fleet/diana/diana3.jpg','/img/fleet/diana/diana4.jpg'),
(2, 'Artemide', 'Sorrento 36 Semi Cabinato', '30 Knots', '2 x 370 hp Ebd - Yanmar', '10,90 mt', 12, '4 + 2', 1, '/img/fleet/artemide/artemide1.jpg','/img/fleet/artemide/artemide2.jpg','/img/fleet/artemide/artemide3.jpg','/img/fleet/artemide/artemide4.jpg'),
(3, 'Venere', 'Gagliotta 37 Fisherman', '34 Knots','2 x 260 hp Volvo Penta D4', '10,30 mt', 12, '4 + 2', 1, '/img/fleet/venere/venere1.jpg','/img/fleet/venere/venere2.jpg','/img/fleet/venere/venere3.jpg','/img/fleet/venere/venere4.jpg'),
(4, 'Luna', '750/G Classic', '28 Knots','2 x 125 hp Ebd - Yanmar', '7,50 mt', 8, '2 + 1', 1, '/img/fleet/luna/luna1.jpg','/img/fleet/luna/luna2.jpg','/img/fleet/luna/luna3.jpg','/img/fleet/luna/luna4.jpg');

insert into "categories" ( "name", "description", "imageUrl", "url")
values ('Excursions', 'A selection of group excursions will give you the opportunity to immerse yourself at 360 degrees in our territory', '../img/cards/excursions.jpg', 'excursions'),
('Wedding Proposal', 'If you are looking for the perfect spot along the Amalfi Coast for an unforgettable marriage proposal, this is the tour for you', '../img/cards/wedding.jpg', 'wedding'),
('Sunset Cruise', 'A sunset cruise is the most relaxing tour ever. Is perfect if you wish to spend just few hours cruising along the Amalfi Coast', '../img/cards/sunset.jpg', 'sunset'),
('Diving', 'Immerse yourself with us along the splendid Amalfi coast, it will be a unique experience into a fantastic underwater world', '../img/cards/diving.jpg', 'diving');

insert into "products" ( "categoryId", "price", "priceId", "shortDescription", "longDescription", "imageUrl", "navigationAreas", "title", "subTitle")
values (1, 750.00, 'price_1L8RkoCVTQvy7wnBkGCcFLni','The Amalfi Coast, UNESCO world heritage site since 1997, visited on board a boat is our best way of taking you to the most famous gem in Italy. On your sojourn around the Amalfi Coast, the rhythm of the journey will be punctuated solely by the sound of your footsteps.', 'The Amalfi Coast offers breathtaking views, kilometres of coast to explore, hidden beaches and coves, natural caves, history and myths that blend together. Indulge in the flavours of the Amalfi Coast, including the unforgettable taste of the sea that you can savour only here.Since Roman times, the Amalfi Coast has enchanted its visitors with its scenery and incredible views, capable of creating pure emotion. Admire the terraced gardens where the vines and lemon trees typical of this land flourish. A magical place, with plenty of beaches and coves that can often be reached only by sea, small rocky bays and inlets between the cobalt blue sea and the cliffs that fall down into the sea.', 'url("/img/excursions/posnotte.jpg")', 'Amalfi / Positano / Praiano / Furore / Ravello / Maiori / Minori / Cetara / Vietri / Salerno', 'Amalfi Coast', 'A sensual blend of both natural and cultural wonders'),
(1, 850.00, 'price_1L8uz6CVTQvy7wnBwGE0aujz','Between sea and sky, let yourself be captivated by the mysteries of the wonders of the Mediterranean. Capri, Ischia and Procida, the three gems of the Campania archipelago, in the shadow of Vesuvius.', 'BlueSea Charter was born here, in the beautiful Gulf of Naples where the three splendid Phlegraean Islands rise out of the water. A cruise on a caique to Capri and around the Gulf of Naples is a fusion of natural beauty and an innate sense of hospitality, the hallmark of its inhabitants. The island of Capri astounds with its deep blue sea, which can be admired even more on a visit the Grotta Azzurra, in the shadow of the rocky peaks known as the Faraglioni, the guardians of the island. And again, the Salto di Tiberio (a precipice overlooking the sea), Punta Tragara, the Grotta Meravigliosa. For lovers of high society and town life, a stop-over in the famous square in Capri and a stroll along the streets lined by all sorts of shops and bars and restaurants à la mode, often frequented by international celebrities, is a must. The island of Ischia, the largest of the three, has been famous since ancient times for its volcanic thermal waters. The island of Procida, the smallest, is a real gem in the Gulf of Naples, with a large protected Marine Area called the Regno di Neptune (Kingdom of Neptune). Capri, Ischia and Procida will be the sensational backdrop of your marvellous yacht cruise.In the evening, in the shadow of the marinas and with the lights reflecting on the sea, you can savour the typical flavours of Naples and Campania, fresh fish caught every day and the tasty traditional desserts.', 'url("/img/excursions/capri.jpg")', 'Capri, Blue Grotto / Faraglioni / Lì Galli Island', 'Capri',  'The simple enchantment of the island of Capri'),
(1, 850.00, 'price_1L8uz6CVTQvy7wnBwGE0aujz','shortDescription', 'longDescription', 'url("/img/excursions/capri.jpg")', 'Capri, Blue Grotto / Faraglioni / Lì Galli Island', 'Capri',  'The simple enchantment of the island of Capri'),
(1, 850.00, 'price_1L8uz6CVTQvy7wnBwGE0aujz','shortDescription', 'longDescription', 'url("/img/excursions/capri.jpg")', 'Capri, Blue Grotto / Faraglioni / Lì Galli Island', 'Capri',  'The simple enchantment of the island of Capri'),
(2, 600.00, 'price_1LADtwCVTQvy7wnBjxMs2sGO','shortDescription', 'longDescription', 'url("/img/excursions/capri.jpg")', 'Capri, Blue Grotto / Faraglioni / Lì Galli Island', 'Wedding Proposal',  'On a gulet on the Amalfi Coast');
